version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 3030:80
      - 3001:81
    volumes:
      - ./php.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3037:9003
    depends_on:
      - mysql
    # command: ["/bin/bash", "-c", "php-fpm -F -R", "&&", "./vendor/bin/propel migration:up"]
    # command: ["/bin/bash", "-c", "./vendor/bin/propel migration:up && php-fpm -F -R"]
    # - ["php-fpm", "-F", "-R"]
  
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'database_dev'
      character_set_server: "utf8mb4"
      collation_server: 'utf8mb4_unicode_ci'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    # command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./client:/client
      # todo: enviroment VITE_URL=http://localhost:3030
    ports:
      - 3031:80
    depends_on:
      - web

# to not store with project
# volumes:
#   mysqldata: {}