version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 3030:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3037:9003
  
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'database_dev'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "mongouser"
  #     MONGO_INITDB_ROOT_PASSWORD: "mongopassword123"
  #   volumes:
  #     - ./mongodata:/data/db
  #   ports:
  #     - 27017:27017


# to not store with project
# volumes:
#   mysqldata: {}